from __future__ import annotations

try:
    from .api_routes import (
        _AsyncHttpClient,
        _AsyncOpenAIClient,
        _build_coach_prompt_package,
        _build_ollama_generate_payload,
        _build_structured_render_prompt,
        _finalize_static_tts_reply,
        _generate_coach_reply,
        _generate_structured_spoken_reply,
        _looks_like_question_echo,
        _looks_like_system_prompt_leak,
        _normalize_compare_text,
        _normalize_final_reply_text,
        _spoken_reply_from_payload,
        _stream_ollama_reply,
        _stream_openai_reply,
        _structured_memory_field_clause,
        _structured_template_reply,
        _text_similarity,
        _token_overlap_ratio,
        _try_general_query_reply_text,
        _validate_structured_reply,
    )
except Exception:
    from api_routes import (
        _AsyncHttpClient,
        _AsyncOpenAIClient,
        _build_coach_prompt_package,
        _build_ollama_generate_payload,
        _build_structured_render_prompt,
        _finalize_static_tts_reply,
        _generate_coach_reply,
        _generate_structured_spoken_reply,
        _looks_like_question_echo,
        _looks_like_system_prompt_leak,
        _normalize_compare_text,
        _normalize_final_reply_text,
        _spoken_reply_from_payload,
        _stream_ollama_reply,
        _stream_openai_reply,
        _structured_memory_field_clause,
        _structured_template_reply,
        _text_similarity,
        _token_overlap_ratio,
        _try_general_query_reply_text,
        _validate_structured_reply,
    )
